#1d
# to get the mean , median and sd. created an array of 1-20 values . and for b. question to get numbers greater then 10 we given arr more thwn 10 ratio.

In [1]:
import numpy as np
import time 


In [2]:
arr=np.arange(1,21)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))


Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [4]:
print("\nIndices of elements greater than 10:")
print(np.where(arr > 10))


Indices of elements greater than 10:
(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


# 2d 
#there rae more ways two solve a question rather than then explaination way .



In [6]:
arr2 = np.arange(1, 17).reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
print("\nTranspose")
print(arr2.T)



Transpose
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [8]:
print("\nRow-wise Sum")
print(np.sum(arr2, axis=1))

print("\nColumn-wise Sum")
print(np.sum(arr2, axis=0))


Row-wise Sum
[10 26 42 58]

Column-wise Sum
[28 32 36 40]


In [11]:
print("\nRow-wise Sum","\nColumn-wise Sum")
print(np.sum(arr2, axis=1))
print(np.sum(arr2, axis=0))

# i tried to way to do it one has less code and other have and additional line .so sir what apporach is better in techinaical asepect 


Row-wise Sum 
Column-wise Sum
[10 26 42 58]
[28 32 36 40]


# 3 question 

In [24]:
a = np.random.randint(1,21,(3,3))
b = np.random.randint(1,21,(3,3))


In [26]:
print("\nAddition")
print(a+b)

print("\nSubtraction")
print(a-b)

print("\nMultiplication")
print(a*b)


Addition
[[35  8 11]
 [ 9 13 13]
 [ 6 33 21]]

Subtraction
[[ -3  -6  -5]
 [ -7   7 -11]
 [  4  -7   3]]

Multiplication
[[304   7  24]
 [  8  30  12]
 [  5 260 108]]


In [27]:
print("\nDot Product")
print(np.dot(a,b))


Dot Product
[[315 175 167]
 [100  57 137]
 [211 314 304]]


# 4 question 

In [28]:
arr3 = np.arange(1,13)

new_arr = arr3.reshape(3,4)

print("Reshaped Array")
print(new_arr)

print("\nSliced Array")
print(new_arr[:2,-2:])

Reshaped Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced Array
[[3 4]
 [7 8]]
