In [10]:
from fractions import Fraction

# define sample  space and outcomes 
coins_outcomes = ['Heads','Tails','Heads']
total_outcomes = len(coins_outcomes)  # total outcome = 2

# calculating probalities dynamacally
prob_heads = Fraction(coins_outcomes.count('Heads'),total_outcomes)
prob_tails = Fraction(coins_outcomes.count('Tails'),total_outcomes)

print("Sample Space:", coins_outcomes)
print("P(Heads)=", prob_heads)
print("P(Tails)", prob_tails )

Sample Space: ['Heads', 'Tails', 'Heads']
P(Heads)= 2/3
P(Tails) 1/3


In [12]:
print(Fraction(1,3))

1/3


In [13]:
def bayes(prior, sensitivity, false_positive):
    return (sensitivity * prior) / (
        sensitivity * prior + false_positive * (1 - prior)
    )

result = bayes(0.001, 0.99, 0.05)
print(result)

0.019434628975265017


In [15]:
print("\n -------- 3 coins tossed : exactly 2 heads ")
from itertools import product

outcome = list(product(['H','T'], repeat = 3 ))
outcome


 -------- 3 coins tossed : exactly 2 heads 


[('H', 'H', 'H'),
 ('H', 'H', 'T'),
 ('H', 'T', 'H'),
 ('H', 'T', 'T'),
 ('T', 'H', 'H'),
 ('T', 'H', 'T'),
 ('T', 'T', 'H'),
 ('T', 'T', 'T')]

In [2]:
# hypotheiss 

# import required libary 

import scipy.stats as stats


In [3]:
# define the busiines and statitical inputs:
# sample size (number of shopers):

n= 80

# sample means weekly spending 
sample_mean = 130

#sample standard deviation

sample_std = 40

# hypothesis population mean 

mu_0 = 120 #dollaes 


In [4]:
# 2 calcluate statitics ]

t_statitics = (sample_mean - mu_0)/ (sample_std/ (n**0.5))
print(t_statitics)

2.23606797749979


In [6]:
## sample for type 1 error and type 2 error 
import numpy as np 

#step 1 : set random result for 10 applicant 

# ground truth : 1 = will not repay the loan , 0 = WILL repay 
# simulate actual behaviour 

actual_behaviour = np.array([0,0,1,0,1,0,0,1,1,0])

# bank behaviour 
# 1 = reject the loan , 0 = will accept the loan 

bank_decison = np.array([0,1,1,0,0,0,0,1,1,0])


In [7]:
actual_behaviour

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0])

In [8]:
bank_decison

array([0, 1, 1, 0, 0, 0, 0, 1, 1, 0])

In [12]:
# step 2 analysis 

for i in range(len(actual_behaviour)):
    print(f"\nApplicant {i+1}:")
    if bank_decison[i] == 0 and actual_behaviour[i] == 0 :     
      print ( " yes Approved and Rapid (coorect)")
    elif  bank_decison[i] == 1 and actual_behaviour[i] == 0 :
      print (" wrong Type 1 Error : Reject But Would have Repaid  ")
    elif bank_decison[i]== 1 and actual_behaviour[i] == 1 : 
      print ( " yes Type II Error : Rejected And Wouldnt pay The Loan ")


Applicant 1:
 yes Approved and Rapid (coorect)

Applicant 2:
 wrong Type 1 Error : Reject But Would have Repaid  

Applicant 3:
 yes Type II Error : Rejected And Wouldnt pay The Loan 

Applicant 4:
 yes Approved and Rapid (coorect)

Applicant 5:

Applicant 6:
 yes Approved and Rapid (coorect)

Applicant 7:
 yes Approved and Rapid (coorect)

Applicant 8:
 yes Type II Error : Rejected And Wouldnt pay The Loan 

Applicant 9:
 yes Type II Error : Rejected And Wouldnt pay The Loan 

Applicant 10:
 yes Approved and Rapid (coorect)


In [ ]:
remedy_medicine = np.array([0,1,12,12,12,54,45,52])

medicine_behaiviour = np.array([0,12,12,12,12,45,45,52])

remedy_medicine

array([ 0,  1, 12, 12, 12, 54, 45, 52])

In [15]:
medicine_behaiviour

array([ 0, 12, 12, 12, 12, 45, 45, 52])

In [17]:
from __future__ import print_function


for i in range(len(remedy_medicine)) :
 print(f"\n applicant {i+n}")
 if remedy_medicine [i] == 0 and medicine_behaiviour [i] == 0 :
     print("Correct this is true ")
 elif remedy_medicine [i]== 1 and medicine_behaiviour[i] == 0 :
      print(" wrong Type I Error : This is not True")
 elif remedy_medicine [i] == 12 and medicine_behaiviour [i]== 12 : 
      print("Wrong Type II Error ; This is not True but not False")

 


 applicant 80
Correct this is true 

 applicant 81

 applicant 82
Wrong Type II Error ; This is not True but not False

 applicant 83
Wrong Type II Error ; This is not True but not False

 applicant 84
Wrong Type II Error ; This is not True but not False

 applicant 85

 applicant 86

 applicant 87
